version: "3.9"
services:
  db:
    image: postgres:13.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "embase_db"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"
