version: "3.9"
services:
  postgres:
    image: postgres:13.5
    environment:
      POSTGRES_DB: "embase_db"
      POSTGRES_USER: "testuser"
      POSTGRES_PASSWORD: "qwerty"
    ports:
      - "5432:5432"